<?php
namespace App\Core\Models;
use Illuminate\Database\Eloquent\Model;
class Posts extends Model
{
    protected $fillable = [
        'title',
        'share_url',
        'slug',
        'excerpt',
        'plain_text',
        'content',
        'tips',
        'album',
        'author_name',
        'user_id',
        'customer_id',
        'status',
        'published_at',
        'thumbnail_url',
        'top_background_url',
        'is_comment',
        'comment_count',
        'post_type',
        'category_type',
        'price',
        'start_date',
        'duration',
        'cost',
        'address',
        'continent',
        'country',
        'province',
        'district',
        'subdistrict',
        'email',
        'telephone',
        'latitude',
        'longitude',
        'website',
        'open_time',
        'ticket_price',
        'original_url',
        'banner_image',
        'banner_url',
        'banner_template',
        'category_id',
        'disease_id',
        'is_deleted',
        'deleted_at',
        'is_highlight',
        'is_editor_pick',
        'is_most_viewed',
        'is_sponsored',
        'bookingram',
        'has_tags',
        'showon_homepage',
        'time_expired_deal',
        'meta_title',
        'meta_keyword',
        'meta_description'
    ];

    const STATUS_PUBLISH = 'publish';
}
